In [1]:
import pandas as pd

In [2]:
myfile = 'www.pangaea.de-access-anon.log.bz2'

In [3]:
logData = pd.read_csv(myfile, sep='\s+',names=['hashed ID','pangea','delete1','t1','t2','log','status','size','delete2','device'],header=None)

In [4]:
logData.head()

,hashed ID,pangea,delete1,t1,t2,log,status,size,delete2,device
0,68aa873d61a6586244b0892d7bca2573,http://www.pangaea.de,-,[30/Sep/2019:06:25:44,+0000],GET /search?ie=UTF-8&q=parameter%3A%22Bathysip...,301,178,-,Mozilla/5.0 (compatible; AhrefsBot/6.1; +http:...
1,a9b74a347fa53fceed817cec4dabe1b0,http://www.pangaea.de,-,[30/Sep/2019:06:25:54,+0000],GET /search?ie=UTF-8&q=PI%3Aemail%3Asinam%40ki...,301,178,-,Mozilla/5.0 (compatible; AhrefsBot/6.1; +http:...
2,55e11990b11106b85a85921f4369485e,https://www.pangaea.de,-,[30/Sep/2019:06:25:54,+0000],GET /search?maxdate=2005-12-31T23%3A59%3A59&mi...,301,519,-,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...
3,75892c86ec3272b7fa79e0f2c375a9f5,https://www.pangaea.de,-,[30/Sep/2019:06:25:56,+0000],GET /?maxdate=2005-12-31T23%3A59%3A59&mindate=...,200,77428,-,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...
4,112f467bd0b8740ee966059ac6ac9979,https://www.pangaea.de,-,[30/Sep/2019:06:26:00,+0000],GET /nosupplement.php?uri=doi%3A10.1016%2Fs037...,200,2925,-,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...

In [5]:
logData['time']=logData['t1']+logData['t2']

In [6]:
logDataModified = logData.drop(['delete1', 'delete2','t1','t2','pangea'], axis=1)

In [7]:
logDataModified

,hashed ID,log,status,size,device,time
0,68aa873d61a6586244b0892d7bca2573,GET /search?ie=UTF-8&q=parameter%3A%22Bathysip...,301,178,Mozilla/5.0 (compatible; AhrefsBot/6.1; +http:...,[30/Sep/2019:06:25:44+0000]
1,a9b74a347fa53fceed817cec4dabe1b0,GET /search?ie=UTF-8&q=PI%3Aemail%3Asinam%40ki...,301,178,Mozilla/5.0 (compatible; AhrefsBot/6.1; +http:...,[30/Sep/2019:06:25:54+0000]
2,55e11990b11106b85a85921f4369485e,GET /search?maxdate=2005-12-31T23%3A59%3A59&mi...,301,519,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...,[30/Sep/2019:06:25:54+0000]
3,75892c86ec3272b7fa79e0f2c375a9f5,GET /?maxdate=2005-12-31T23%3A59%3A59&mindate=...,200,77428,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...,[30/Sep/2019:06:25:56+0000]
4,112f467bd0b8740ee966059ac6ac9979,GET /nosupplement.php?uri=doi%3A10.1016%2Fs037...,200,2925,Mozilla/5.0 (compatible; SemrushBot/6~bl; +htt...,[30/Sep/2019:06:26:00+0000]
...,...,...,...,...,...,...
3874083,6cfe6735394bde66910dd1d72a849848,GET /?count=10&q=parameter%3A%22Bartonella+bir...,200,61170,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http:...,[25/Nov/2019:06:26:08+0000]
3874084,6cfe6735394bde66910dd1d72a849848,GET /search?ie=UTF-8&count=10&q=parameter:%22B...,301,178,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http:...,[25/Nov/2019:06:26:09+0000]
3874085,6cfe6735394bde66910dd1d72a849848,GET /search?ie=UTF-8&count=10&q=parameter:%22B...,301,357,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http:...,[25/Nov/2019:06:26:11+0000]
3874086,6cfe6735394bde66910dd1d72a849848,GET /search?ie=UTF-8&count=10&q=parameter:%22B...,301,178,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http:...,[25/Nov/2019:06:26:17+0000]
3874087,6cfe6735394bde66910dd1d72a849848,GET /search?ie=UTF-8&count=10&q=parameter:%22B...,301,178,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http:...,[25/Nov/2019:06:26:22+0000]

In [8]:
def string_check(log):
    if 'GET /advanced/search' in str(log): 
        if 'facets=' in str(log) :
            if 'parameter' in str(log):
                return False
            else:
                return True
        else:
            return False
    else: 
        return False

In [9]:
boolSearch = logDataModified['log'].apply(lambda x: string_check(x))

In [10]:
searchData = logDataModified[boolSearch]

In [11]:
searchData

,hashed ID,log,status,size,device,time
222,d4057bb28680f2e23657e0afd66e3a2c,GET /advanced/search.php?facets=default&q=proj...,200,1668,Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleW...,[30/Sep/2019:06:33:57+0000]
311,d4057bb28680f2e23657e0afd66e3a2c,GET /advanced/search.php?facets=default&q=proj...,200,1709,Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleW...,[30/Sep/2019:06:34:15+0000]
350,b1b3c3c347a005c5dc00aa0953e985a5,GET /advanced/search.php?q=*&count=0&facets=ma...,200,645,Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like...,[30/Sep/2019:06:34:38+0000]
363,baf86b31f2e4bf22cf057b110b778f8c,GET /advanced/search.php?q=*&count=0&facets=ma...,200,654,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,[30/Sep/2019:06:34:42+0000]
375,b1b3c3c347a005c5dc00aa0953e985a5,GET /advanced/search.php?facets=default&t=Ocea...,200,3890,Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like...,[30/Sep/2019:06:34:43+0000]
...,...,...,...,...,...,...
3873796,ae4433f1629e06d9de50d4450d4e7938,GET /advanced/search.php?facets=default&q=para...,200,3063,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,[25/Nov/2019:06:16:30+0000]
3873800,815d88f2e0c91c24599da86eede112d1,GET /advanced/search.php?facets=default&q=PI%3...,200,2449,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,[25/Nov/2019:06:16:41+0000]
3873866,815d88f2e0c91c24599da86eede112d1,GET /advanced/search.php?facets=default&q=PI%3...,200,1982,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,[25/Nov/2019:06:20:36+0000]
3873905,30e9522666ec01f9629e7196ff7ca57e,GET /advanced/search.php?facets=default&q=PI%3...,200,2682,Mozilla/5.0 (Linux; Android 6.0; A97 Build/MRA...,[25/Nov/2019:06:21:45+0000]
3873942,aaca9868e11cfc4b413d7825dbb2a960,GET /advanced/search.php?facets=default&q=nodu...,200,3459,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,[25/Nov/2019:06:23:21+0000]

In [34]:
facets = searchData['log'].apply(lambda log: log.split('facets=')[1].split('&')[0].split('%')[0].split(' ')[0].lower())

In [37]:
topFacets = facets.value_counts()

In [38]:
topFacets.to_csv('Top_Facets')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [39]:
pd.read_csv('Top_Facets',names=['Facet','Count'],header=None)

       Facet  Count
0    default  49489
1  maintopic  21584
2     author   1878
3      topic   1152
4   location   1128
5    pubyear    809
6    project    601
7     device    537
8   campaign    487
9      basis    138